version: '3.1'
services:
  app:
    image: node:18-slim@sha256:b175cd7f3358c399f7bcee9b1032b86b71b1afa4cfb4dd0db55d66f871475a3e
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4015:4015'
    volumes:
      - ./:/app
    env_file:
      - .docker/local.env
      - .env
    environment:
      - NODE_ENV=local
    entrypoint: ./.docker/scripts/local-start.sh
    depends_on:
      - snowplow

  localstack:
    image: localstack/localstack:1.2
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=sqs
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  snowplow:
    image: pocket/snowplow-micro:latest
    platform: linux/amd64
    ports:
      - '9090:9090'
